### PR TITLE
Add support for unharmonised metadata

### LINKED ISSUE #95: "Author Categories" accessible?
Hi developers,

Quick question: is it possible to obtain the cell metadata that are flagged as "Author categories" on the cellxgene website using `CuratedAtlasQueryR`?

An example, I am looking at [this](https://cellxgene.cziscience.com/e/c7775e88-49bf-4ba2-a03b-93f00447c958.cxg/) dataset on the cellxgene website. I can obtain a subset of cells e.g. by

```{r}
sce_sub <- metadata |>
    dplyr::filter(
        name == "Single-cell multi-omics analysis of the immune response in COVID-19",
        cell_type == "plasmablast",
        disease %in% c("COVID-19",
                       "normal")
    ) |>
    get_SingleCellExperiment()
```

When looking at the `colData`, I don't seem to have any of the information that is flagged on the website as "Author Categories".  Some of which in this case may be invaluable (smoking status, outcome, days from onset, ...).

How can I obtain these variables for my selected cells?

Very nice package by the way, congrats!

### PR DESCRIPTION
**Pull request by multimeric**
* Add `get_unharmonised_metadata()` (fix #95)
* Added tests to support this new function
* Add `update_unharmonised()` internal function to support updating this repository

### CODE REVIEW

**Comment by multimeric** [comment]
I need some help adding the command we use for building wheels. `python setup.py sdist_wheel` doesn't seem to work.

**Review by stemangiola — APPROVED** [review]

**Review by stemangiola — CHANGES_REQUESTED** [review]
Could you please add the example to README?

**Comment by multimeric** [comment]
> Could you please add the example to README?

Do I have to update both the readme and the vignette whenever I want to change the readme?

**Comment by stemangiola** [comment]
> * get_unharmonised_metadata



> > Could you please add the example to README?
> 
> Do I have to update both the readme and the vignette whenever I want to change the readme?

That would be appreciated, just copy and paste. I know it's annoying but at the moment let's go with this methosd.

**Comment by jgilis** [comment]
Hi @stemangiola and @multimeric, 

Exactly what I had in mind when opening issue #95, thanks!

One minor suggestion for the README, in stead of using `dataset = "838ea006-2369-4e2c-b426-b2a744a2b02b"`,  maybe extract it programatically from the `metadata` or at least mention it must be an entry for the `file_id` column. I first assumed it was an entry for the `dataset_id` column of the `metadata`. I guess it could be seen from the downstream `left_join` call, but it's easy to miss.

Best regards,

Jeroen

**Comment by multimeric** [comment]
There might be an argument to supporting both APIs? The current `get_unharmonised_metadata()`, as we discussed, can be a simpler lower level API since it takes only a vector of IDs. This proposed function could coexist with that, as a high level function that takes the metadata frame, and adds the cell filtering on top of that.

**Comment by stemangiola** [comment]
I feel the `metadata` to `unharnomised metadata` stream would make the `file_id` query stream. We can start using our function as backend (that already does all heavy lifting), and export it if we see that the community asks.

I think so, because the "new" interface would
- be consistent with our logic of using metadata as input for stuff, so keey the rules of the game simple and few
- not force the users to know what `file_id` is but present it in the output, lowering the barrier-to-entry of using our `get_unharmonised_metadata()`

**Comment by multimeric** [comment]
In we're committing to making this a high level API, should I make it more user friendly by actually annotating the unharmonised data as a nested list per cell? e.g.
```
file_id | cell_   | ... | unharmonised
<chr>   | <chr>   | ... | <named list>
```

**Comment by stemangiola** [comment]
I appreciate e this perspective, but I would tend to not to, for two reasons (but I'm open to discussion):

- nesting by cell_ would increase x10 the memory imprint
- nesting by file_id communicated the non-harmonisability at the cell level without even reading the documentation and would guide the user to do dataset-by-dataset operations, which are actually the only possible operations. While cell_ grouping would implicitly communicate a level of abstraction that is actually not there, and the documentation will be responsible for limiting/guiding invalid user actions.

**Comment by multimeric** [comment]
I think memory footprint isn't an enormous issue because the unharmonised metadata will be the same size whether or not it's joined to the harmonised metadata table (note: the `unharmonised` column I'm proposing is a simple list, not the entire dataset data frame). I can't argue with the second point though.

**Comment by stemangiola** [comment]
I see. For the sake of UI design I would still vote for nesting by `file_id`, but I will be open to pivot if user feedback point on your logics more.

@jgilis any opinion between the 2 alternatives?

**Comment by jgilis** [comment]
My answer would depend on your answer to this question. Say I'm interested in only some cell types in (1) one dataset, or (2) in multiple datasets. Do you see any disadvantages of the `file_id` strategy as compared to the `cell_` strategy in these scenarios?

**Comment by stemangiola** [comment]
> Using the `file_id` strategy, would it be possible for the added `unharmonised metadata` to only contain info on cells of those selected cell types or not?

This should already be in the design (@multimeric?)



> Say I'm interested in only some but not all cell types in (1) one dataset, or (2) in multiple datasets. Do you see any disadvantages of the `file_id` strategy as compared to the `cell_` strategy in these scenarios?

Not really, for 

(1) you must `unnest` and `left_join` for the `file_id` nesting, or only left_join fgor the `cell_` nesting, for 
(2) you must do separate operations by `fil_id` for `file_id` nesting, or `nest` and  do separate operations by `fil_id` for `cell_` nesting

Conclusion: for the moment, without any concert from @jgilis we'll implement the `file_id` nesting.

**Comment by jgilis** [comment]
I see, then indeed no further concerns from my side!

**Comment by multimeric** [comment]
> Using the file_id strategy, would it be possible for the added unharmonised metadata to only contain info on cells of those selected cell types or not?

Yes, the proposed (#99) design is such that unharmonised metadata is only returned for cells that you have selected. So if you filter down to a certain cell type, you will only get metadata for that cell type

**Pull request merged**
