### PR TITLE
metadata accepts multiple databases

### PR DESCRIPTION
**Pull request by myushen**

### CODE REVIEW

**Comment by multimeric** [comment]
Does this implement the metadata functionality without the count data functionality? A pull request description would be helpful here.

**Comment by myushen** [comment]
yes, checkout from a previous commit that passed testing. plan to move count data functionality implementation into another branch, and another pull request

**Comment by stemangiola** [comment]
> yes, checkout from a previous commit that passed testing. plan to move count data functionality implementation into another branch, and another pull request

As metadata with no counts would not lead to a functioning API, maybe add the count branch to this branch (or commit directly to this branch). And push to github so this PR i updated.

Is the count work ready right? I thought so, in that case you can merge it here. No need to create a separate PR.

**Comment by stemangiola** [comment]
Congrats @myushen

**Pull request merged**
